shopt -s expand_aliases

. ~/.bash/env
. ~/.bash/aliases
. ~/.bash/functions
. ~/.bash/config

if [ -f ~/.bash_private ]; then
  . ~/.bash/private
fi

. `brew --prefix`/etc/profile.d/z.sh

if $(grc &>/dev/null)
then
  source `brew --prefix`/etc/grc.bashrc
fi

eval "$(rbenv init -)"

